---
- hosts: pves
  gather_facts: no
  remote_user: root
  vars:
  vars_files:
    - /home/kmonti/vars.yml
  tasks:
  - name: Create New VM
    proxmox_kvm:
      api_user    : root@pam
      api_password: "{{ password }}"
      api_host    : pve
      name        : "{{ item }}" 
      node        : pve
      format      : qcow
      timeout     : 300  
      net         : '{"net0":"virtio,bridge=vmbr1,rate=200"}'
      virtio: '{"ide0":"{{ storage }}:{{ disk_size }},cache=writeback"}'
      cores: 1
      memory: "{{ memory_size }}"
      balloon: 512
      net         : '{"net0":"virtio,bridge=vmbr0,rate=200"}'
      virtio: '{"virtio0":"{{ storage }}:{{ disk_size }}"}'
    with_items: "{{ machines }}"
  - pause:
      seconds: 3

  - name: start
    proxmox_kvm:
      api_user    : root@pam
      api_password: "{{ password }}"
      api_host    : pve
      #clone       : open61template
      name        : "{{ item }}" 
      node        : pve
      state       : started
    with_items: "{{ machines }}"

