---
- hosts: pves
  gather_facts: no
  remote_user: root
  vars:
  vars_files:
    - /tmp/vars.yml
  tasks:
  - name: Clone for Create New VM
    proxmox_kvm:
      api_user    : root@pam
      api_password: "{{ password }}"
      api_host    : pve
      #clone       : open61template
      name        : "{{ item }}" 
      node        : pve
      format      : raw
      timeout     : 300  
      net         : '{"net0":"virtio,bridge=vmbr1,rate=200"}'
      virtio: '{"ide0":"{{ storage }}:{{ disk_size }},cache=writeback"}'
      cores: 1
      memory: "{{ memory_size }}"
      balloon: 512
    with_items: "{{ contents }}"
    #with_items: "smoke1"

  - name: start
    proxmox_kvm:
      api_user    : root@pam
      api_password: "{{ password }}"
      api_host    : pve
      #clone       : open61template
      name        : "{{ item }}" 
      node        : pve
      timeout     : 300  
      state: started
    with_items: "{{ contents }}"
    #with_items: "smoke1"

