---
- hosts: pves
  gather_facts: no
  remote_user: root
  vars:
  vars_files:
    - /tmp/vars.yml
  tasks:
  - name: Clone for Create New VM
    proxmox_kvm:
      api_user    : root@pam
      api_password: "{{ password }}"
      api_host    : pve
      clone       : open61template
      name        : "{{ item }}" 
      node        : pve
      format      : raw
      timeout     : 300  
    with_items: "{{ contents }}"

  - name: start vm
    proxmox_kvm:
      api_user    : root@pam
      api_password: "{{ password }}"
      api_host    : pve
      name        : "{{ item }}" 
      node        : pve
      state       : started
    with_items: "{{ contents }}"

  - name: get ip
    command: getip.sh "{{item}}"
    register: "r"
    with_items: "{{ contents }}"
  - debug: var=r
  - debug: msg="item.stdout={{item.stdout}}"
    with_items: "{{r.results}}"

  - name: set facts
    set_fact:
      #"{{ item }}": "{{ item.stdout}}"
      item: "{{ item.stdout }}"
    with_items: "{{r.results}}"
  - debug: var=item

- hosts: router
  gather_facts: no
  remote_user: root
  tasks:
  - name: iptables
    command: ping "{{ item }}"
    #with_items: "{{r.stdout}}"
    #with_items: "{{r.results}}"
  tags: router
