---
- hosts: pves
  gather_facts: no
  remote_user: root
  vars:
  vars_files:
    - /home/kmonti/vars.yml
  tasks:
  - name: Create New VM
    proxmox_kvm:
      api_user    : root@pam
      api_password: "{{ password }}"
      api_host    : pve
      name        : "{{ item }}" 
      node        : pve
      format      : qcow
      timeout     : 300  
    with_items: "{{ machines }}"

  - name: start vm
    proxmox_kvm:
      api_user    : root@pam
      api_password: "{{ password }}"
      api_host    : pve
      name        : "{{ item }}" 
      node        : pve
      state       : started
    with_items: "{{ machines }}"

