---
- hosts: pves
  vars:
  vars_files:
    - /home/kmonti/vars.yml
  gather_facts: no
  remote_user: root
  tasks:
  - name: stop vm
    proxmox_kvm:
      api_user    : root@pam
      api_password: "{{ password }}"
      api_host    : pve
      name        : "{{ item }}" 
      node        : pve
      state	  : stopped
      force       : yes
      timeout     : 300  
    with_items: "{{ machines }}"

  - name: destroy vm
    proxmox_kvm:
      api_user    : root@pam
      api_password: "{{ password }}"
      api_host    : pve
      name        : "{{ item }}" 
      node        : pve
      state       : absent
    with_items: "{{ machines }}"
